# Generated by Django 3.2 on 2023-08-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roadlines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
