# Generated by Django 3.2 on 2023-08-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roadlines', '0002_alter_driver_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
